### ISSUE TITLE
Run benchmark on Graviton3 instance

### ISSUE THREAD

**Issue by mikemccand** [Tony-X/search-benchmark-game#36]
I am curious how the performance difference between the two engines differs between a modern `aarch64` (e.g. Graviton3) and a modern x86-64 box.

For starters let's just run the "Tantivy vs Lucene" benchmark on a Graviton3 instance?

Separately we can try to find "similar" `aarch64` and `x86-64` instances and compare performance of each engine across those.

**Comment by mikemccand** [comment]
I ran `make index` and `make bench` once on a Graviton instance (not sure if it's Graviton 1, 2, or 3).  Here are the `cat /proc/cpuinfo` flags:

```
processor       : 15
BogoMIPS        : 243.75
Features        : fp asimd evtstrm aes pmull sha1 sha2 crc32 atomics fphp asimdhp cpuid asimdrdm lrcpc dcpop asimddp ssbs
CPU implementer : 0x41
CPU architecture: 8
CPU variant     : 0x3
CPU part        : 0xd0c
CPU revision    : 1
```

I'll try to attach the results.json here -- I haven't yet tried to interpret the results.

**Comment by mikemccand** [comment]
[results.json.gz](https://github.com/Tony-X/search-benchmark-game/files/11905194/results.json.gz)

**Comment by slow-J** [comment]
Ran benchmarks on 3 hosts.

Hardware EC2 instances:
x86_64: m5.12xlarge - 48 virtual CPU, 192 GiB memory, 
Graviton 2: m6g.4xlarge - 16 virtual CPU, 64 GiB memory
Graviton 3: m7g.4xlarge - 16 virtual CPU, 64 GiB memory

![image](https://github.com/Tony-X/search-benchmark-game/assets/32519034/22905c8b-b4bb-4e95-aa12-29b89cb70d2c)
and json:
[results.json.zip](https://github.com/Tony-X/search-benchmark-game/files/12380688/results.json.zip)

Lucene is strangely fast on Graviton 3!

The reason why the Graviton 2 is slower than x86_64 is because the hardware used for the x86_64 machine is much beefier (3x the cost of the Graviton 2 host).

I am re-running the benchmarks just to confirm that these results on Graviton 3 hold up...

**Comment by slow-J** [comment]
Graviton3 results seem to be holding up.

Results from subsequent Graviton3 run (re-indexed and re-ran benchmark):
![image](https://github.com/Tony-X/search-benchmark-game/assets/32519034/076489e0-ce1a-4261-97ba-52502c76b084)

[results_graviton3_21_aug.json.zip](https://github.com/Tony-X/search-benchmark-game/files/12394227/results_graviton3_21_aug.json.zip)

**Comment by Tony-X** [comment]
@slow-J thanks for trying this out! 

For the screenshot, which task is it comparing? COUNT or TOP_10_COUNT ?

**Comment by slow-J** [comment]
Sorry should have been specific, this is COUNT in the screenshot above.

The TOP_10_COUNT still has a large disparity, as seen below:
![image](https://github.com/Tony-X/search-benchmark-game/assets/32519034/3c5004f9-6d64-40b1-a19a-a095f42aeca0)

**Comment by Tony-X** [comment]
no worries! COUNT does take a way quite a bit of works. Actually Lucene 9.7 becomes faster on COUNT for disjunctive queries due to this [optimization](https://github.com/apache/lucene/issues/12358) which is inspired by the work from our [benchmarks](https://github.com/Tony-X/search-benchmark-game/issues/30#issuecomment-1579761787) :)

**Comment by slow-J** [comment]
Yeah COUNT is drastically quicker in Lucene 9.7, thanks to the linked optimizations. And tested in https://github.com/Tony-X/search-benchmark-game/pull/48 .

Attaching also a screenshot (from the same results.json as in comments above) pointing out the massive performance improvement of TOP_10_COUNT between graviton 2 and graviton 3 for both search engines.

![image](https://github.com/Tony-X/search-benchmark-game/assets/32519034/40d1350b-ab14-4f4e-924b-f84453589d0c)

**Comment by slow-J** [comment]
@mikemccand wondering is there any other work remaining in the issue that we haven't yet covered?

**Comment by mikemccand** [comment]
I think this is done!  Let's resolve?  Thanks @slow-J -- these are very exciting results.  Fascinating that `COUNT` on Graviton3 brings Lucene to parity with Tantivy, averaged across all queries.
